---
#
# Hardening Tomcat
#

- name: copy recommended default applications
  command: "cp -r --preserve=mode,ownership,timestamps {{ tomcat_catalina_home }}/webapps/{{ item }} {{ tomcat_catalina_base }}/webapps/{{ item }}"
  args:
    creates: "{{ tomcat_catalina_base }}/webapps/{{ item }}/"
  with_items:
    - "{{ tomcat_copy_webapps }}"

- name: generate manager context file
  template:
    src: manager-context.xml.j2
    dest: "{{ tomcat_catalina_base }}/webapps/manager/META-INF/context.xml"
    owner: "{{ tomcat_system_user }}"
    group: "{{ tomcat_system_group }}"
    mode: 0640
