---
- name: systemd reload
  become: true
  systemd:
    daemon_reload: true
  listen: 'systemd daemon reload'

- name: restart tomcat
  service:
    name: '{{ tomcat_system_name }}'
    state: restarted
    enabled: '{{ tomcat_service_enabled }}'
  listen: 'restart tomcat services'
