---
- name: install init packages for CentOS 7
  hosts: all
  gather_facts: false
  tasks:
    - name: install initscripts package for CentOS 7
      raw: yum install -y initscripts
      become: true
      changed_when: false
- name: Converge
  hosts: all
  vars:
    tomcat_installer_force_download: true
    tomcat_installer_force_overwrite: false
    tomcat_installer_keep: true
    tomcat_installer_local: true
    tomcat_force_update: false
    tomcat_manage_firewalld: false
    tomcat_enable_firewalld: false
  roles:
    - role: ansible-role-tomcat
