---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: java-centos7-11-jdk
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk
      - centos7
      - no_firewalld

  - name: java-centos7-11-jdk-firewalld
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk
      - centos7
      - firewalld

  - name: java-centos7-11-jdk-firewalld-with-source
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk
      - centos7
      - firewalld
      - firewalld_source

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server_jre:
        java_type: 'serverjre'
      ubuntu14:
        tomcat_manage_firewalld: false
      ubuntu16:
        tomcat_manage_firewalld: false
      ubuntu18:
        tomcat_manage_firewalld: false
      centos6:
        tomcat_manage_firewalld: false
      centos7:
        tomcat_manage_firewalld: true
      centos8:
        tomcat_manage_firewalld: true
      no_firewalld:
        tomcat_manage_firewalld: false
      firewalld:
        tomcat_manage_firewalld: true
      firewalld_source:
        tomcat_manage_firewalld_use_zone: false
      ubuntu:
        tomcat_manage_firewalld: false
      python3:
        ansible_python_interpreter: '/usr/bin/env python3'
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
