---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: tomcat-centos6-10-jdk
    image: centos
    image_version: 6.8
    groups:
      - jdk
      - centos6

  - name: tomcat-centos6-10-server-jre
    image: centos
    image_version: 6.8
    groups:
      - server-jre
      - centos6

  - name: tomcat-centos7-10-jdk
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk
      - centos7

  - name: tomcat-centos7-10-server-jre
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - server-jre
      - centos7

  - name: tomcat-centos7-10-jdk-firewalld-source
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - jdk
      - centos7
      - firewalld_source

  - name: tomcat-centos7-10-server-jre-firewalld-source
    image: milcom/centos7-systemd
    image_version: latest
    privileged: true
    groups:
      - server-jre
      - centos7
      - firewalld_source

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      jdk:
        java_type: 'jdk'
      server-jre:
        java_type: 'serverjre'
      centos6:
        tomcat_manage_firewalld: false
      centos7:
        tomcat_manage_firewalld: true
      firewalld_source:
        tomcat_manage_firewalld_use_zone: false
      ubuntu:
        tomcat_manage_firewalld: false
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
